CREATE TABLE CLIENTES(
    CLIE_ID SERIAL NOT NULL,
    CLIE_NOMBRES VARCHAR (50),
    CLIE_APELLIDOS VARCHAR (50),
    CLIE_GENERO VARCHAR (15),
    CLIE_CORREO VARCHAR (30),
    CLIE_DIRECCION VARCHAR (25),
    CLIE_TELEFONO INTEGER,
    CLIE_PAIS VARCHAR (15),
    CLIE_NIT INTEGER,
    CLIE_PASSWORD VARCHAR (250),
    CLIE_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (CLIE_ID)
);

CREATE TABLE EMPLEADOS(
    EMP_ID SERIAL NOT NULL,
    EMP_NOMBRES VARCHAR (50),
    EMP_APELLIDOS VARCHAR (50),
    EMP_TELEFONO INTEGER,
    EMP_CARGO VARCHAR (15),
    EMP_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (EMP_ID)
);

CREATE TABLE HABITACION(
    HABI_ID SERIAL NOT NULL,
    HABI_TIPO VARCHAR (15),
    HABI_PRECIO DECIMAL (10,2),
    HABI_DESCRIPCION VARCHAR (50),
    HABI_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (HABI_ID)
);
