CREATE TABLE CLIENTES(
    CLIE_ID SERIAL NOT NULL,
    CLIE_NOMBRES VARCHAR (50),
    CLIE_APELLIDOS VARCHAR (50),
    CLIE_GENERO VARCHAR (15),
    CLIE_CORREO VARCHAR (30),
    CLIE_DIRECCION VARCHAR (25),
    CLIE_TELEFONO INTEGER,
    CLIE_PAIS VARCHAR (15),
    CLIE_NIT INTEGER,
    CLIE_PASSWORD VARCHAR (250),
    CLIE_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (CLIE_ID)
);

CREATE TABLE EMPLEADOS(
    EMP_ID SERIAL NOT NULL,
    EMP_NOMBRES VARCHAR (50),
    EMP_APELLIDOS VARCHAR (50),
    EMP_TELEFONO INTEGER,
    EMP_CARGO VARCHAR (15),
    EMP_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (EMP_ID)
);

CREATE TABLE HABITACION(
    HABI_ID SERIAL NOT NULL,
    HABI_TIPO VARCHAR (15),
    HABI_PRECIO DECIMAL (10,2),
    HABI_DESCRIPCION VARCHAR (50),
    HABI_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (HABI_ID)
);

CREATE TABLE RESERVACION(
    RESER_ID SERIAL NOT NULL,
    RESER_CLIENTE INTEGER,
    RESER_HABITACION INTEGER,
    RESER_FECHA_ENTRADA DATETIME YEAR TO MINUTE,
    RESER_FECHA_SALIDA DATETIME YEAR TO MINUTE,
    RESER_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (RESER_ID),
    FOREIGN KEY (RESER_CLIENTE) REFERENCES CLIENTES (CLIE_ID),
    FOREIGN KEY (RESER_HABITACION) REFERENCES HABITACION (HABI_ID)
);

CREATE TABLE DETALLE_FACTURA(
    DETA_ID SERIAL NOT NULL,ç
    DETA_EMPLEADO INTEGER,
    DETA_RESERVACION INTEGER,
    DETA_TOTAL DECIMAL (10,2),
    DETA_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (DETA_ID),
    FOREIGN KEY (DETA_CLIENTE) REFERENCES CLIENTES (CLIE_ID),
    FOREIGN KEY (DETA_EMPLEADO) REFERENCES EMPLEADO (EMP_ID),
    FOREIGN KEY (DETA_RESERVACION) REFERENCES RESERVACION (RESER_ID)
);