CREATE TABLE CLIENTES(
    CLIE_ID SERIAL NOT NULL,
    CLIE_NOMBRES VARCHAR (50),
    CLIE_APELLIDOS VARCHAR (50),
    CLIE_GENERO VARCHAR (15),
    CLIE_CORREO VARCHAR (30),
    CLIE_DIRECCION VARCHAR (25),
    CLIE_TELEFONO INTEGER,
    CLIE_PAIS VARCHAR (15),
    CLIE_NIT INTEGER,
    CLIE_PASSWORD VARCHAR (250),
    CLIE_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (CLIE_ID)
);

CREATE TABLE EMPLEADOS(
    EMP_ID SERIAL NOT NULL,
    EMP_NOMBRES VARCHAR (50),
    EMP_APELLIDOS VARCHAR (50),
    EMP_TELEFONO INTEGER,
    EMP_CARGO VARCHAR (15),
    EMP_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (EMP_ID)
);

CREATE TABLE HABITACION(
    HABI_ID SERIAL NOT NULL,
    HABI_TIPO VARCHAR (15),
    HABI_PRECIO DECIMAL (10,2),
    HABI_DESCRIPCION VARCHAR (50),
    HABI_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (HABI_ID)
);

CREATE TABLE RESERVACION(
    RESER_ID SERIAL NOT NULL,
    RESER_CLIENTE INTEGER,
    RESER_HABITACION INTEGER,
    RESER_FECHA_ENTRADA DATETIME YEAR TO MINUTE,
    RESER_FECHA_SALIDA DATETIME YEAR TO MINUTE,
    RESER_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (RESER_ID),
    FOREIGN KEY (RESER_CLIENTE) REFERENCES CLIENTES (CLIE_ID),
    FOREIGN KEY (RESER_HABITACION) REFERENCES HABITACION (HABI_ID)
);

CREATE TABLE DETALLE_FACTURA(
    DETA_ID SERIAL NOT NULL,ç
    DETA_EMPLEADO INTEGER,
    DETA_RESERVACION INTEGER,
    DETA_TOTAL DECIMAL (10,2),
    DETA_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (DETA_ID),
    FOREIGN KEY (DETA_CLIENTE) REFERENCES CLIENTES (CLIE_ID),
    FOREIGN KEY (DETA_EMPLEADO) REFERENCES EMPLEADO (EMP_ID),
    FOREIGN KEY (DETA_RESERVACION) REFERENCES RESERVACION (RESER_ID)
);

--  CREACION DE TABLAS PARA CREACION DE LOGIN Y INSERTS PARA CREACION DE TRES USUARIOS CON DIFERENTES PERMISOS


CREATE TABLE APLICACION (
    APP_ID SERIAL,
    APP_NOMBRE VARCHAR(50),
    APP_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (APP_ID)
);


CREATE TABLE ROL (
    ROL_ID SERIAL,
    ROL_NOMBRE VARCHAR(50),
    ROL_NOMBRE_CT VARCHAR(10),
    ROL_APP INTEGER,
    ROL_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (ROL_ID),
    FOREIGN KEY (ROL_APP) REFERENCES APLICACION (APP_ID)
);

CREATE TABLE USUARIO (
    USU_ID SERIAL,
    USU_NOMBRE VARCHAR(50),
    USU_NIT INTEGER,
    USU_PASSWORD VARCHAR(250),
    USU_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (USU_ID)
);

CREATE TABLE PERMISO (
    PERMISO_ID SERIAL,
    PERMISO_USUARIO INTEGER,
    PERMISO_ROL INTEGER,
    PERMISO_SITUACION SMALLINT DEFAULT 1,
    PRIMARY KEY (PERMISO_ID),
    FOREIGN KEY (PERMISO_ROL) REFERENCES ROL (ROL_ID),
    FOREIGN KEY (PERMISO_USUARIO) REFERENCES USUARIO (USU_ID)
);

-- INSERTS

insert into aplicacion (app_nombre) values ('hotel');

-- INSERTS DE TRES ROLES DIFERENTES CADA UNO TIENE COMO CONTRASEÑA 123456 

insert into rol (rol_nombre, rol_nombre_ct, rol_app ) values ('ADMINISTRADOR DE TIENDA', 'TIENDA_ADM', 1);
insert into rol (rol_nombre, rol_nombre_ct, rol_app ) values ('USUARIO DE TIENDA', 'TIENDA_EMP', 1);
insert into rol (rol_nombre, rol_nombre_ct, rol_app ) values ('USUARIO DE TIENDA', 'TIENDA_USE', 1);


-- USUARIO CON ROL DE ADMINISTRADOR
insert into usuario (usu_nombre, usu_nit, usu_password ) values ('Nixon', 623041, '$2y$10$Nz6/ESQw7b7xW1Q2j.WEM.g5LQ/NSSmHnhZpfolFAH.ltD0GGRKGS');

insert into permiso (permiso_usuario, permiso_rol) values (1, 1);


-- USUARIO CON ROL DE EMPLEADO
insert into usuario (usu_nombre, usu_nit, usu_password ) values ('jean', 1999, '$2y$10$Nz6/ESQw7b7xW1Q2j.WEM.g5LQ/NSSmHnhZpfolFAH.ltD0GGRKGS');

insert into permiso (permiso_usuario, permiso_rol) values (2, 2);

-- USUARIO CON ROL DE USUARIO
insert into usuario (usu_nombre, usu_nit, usu_password ) values ('chocoj', 1998, '$2y$10$Nz6/ESQw7b7xW1Q2j.WEM.g5LQ/NSSmHnhZpfolFAH.ltD0GGRKGS');

insert into permiso (permiso_usuario, permiso_rol) values (3, 3);